[package]
name = "evildoer-registry-statusline"
description = "Statusline segment registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
evildoer-registry-core.workspace = true
linkme.workspace = true
paste.workspace = true
