[package]
name = "evildoer-registry-notifications"
description = "Notification registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
evildoer-registry-core.workspace = true
linkme.workspace = true
thiserror.workspace = true
