[package]
name = "evildoer-registry-panels"
description = "Panel registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
evildoer-base.workspace = true
evildoer-registry-motions.workspace = true
linkme.workspace = true
paste.workspace = true
